### ISSUE TITLE
Unable to configure vent polling interval

### ISSUE THREAD

**Issue by ydogandjiev** [yracine/keenhome.device-type#5]
Hey @yracine, it doesn't seem like its possible to follow these steps of the installation process any longer because the SmartThings Classic app has been retired and is completely unusable (for me at least): 
> # 3) Configure the new device settings in the smartThing classic app</b>
> a) Go to the Home tab, click on Things, and the right device
> b) Hit the configure tile to set the new 'refresh rate' settings.
> You need to press the configure tile for each device that you have.
> Hitting the configure button will no do anything in the UI, but it will change the polling rate (5-10 minutes instead of 1 minute polling) in the list of events.

Is there any other way to configure the vents' polling interval?

**Comment by yracine** [comment]
Hi,

Use webCore and call the configure method.  The new Samsung connect app doesn't allow it for the moment. I don't know if there is any plan to support it in the long term.  This is a ST platform issue out of my control.
